package com.practicum.shoppinglist.presentation.ui.main

data class MainScreenActions(
    val onSearchClick: () -> Unit = {},
    val onDeleteClick: () -> Unit = {},
    val onThemeClick: () -> Unit = {},
    val onAddClick: () -> Unit = {},
    val onAddListDismiss: () -> Unit = {},
    val onNewListNameChange: (String) -> Unit = {},
    val onCreateListClick: () -> Unit = {},
    val onIconPickerDismiss: () -> Unit = {},
    val onShoppingListIconClick: (Long) -> Unit = {},
    val onIconSelected: (String) -> Unit = {},
    val onShoppingListScrollHandled: () -> Unit = {},
    val onRetryClick: () -> Unit = {},
    val onSearchBack: () -> Unit = {},
    val onSearchQueryChange: (String) -> Unit = {},
    val onDeleteAllConfirm: () -> Unit = {},
    val onDeleteAllDismiss: () -> Unit = {},
    val onDeleteListClick: (Long) -> Unit = {},
    val onDeleteListConfirm: () -> Unit = {},
    val onDeleteListDismiss: () -> Unit = {},
    val onCopyListClick: (Long, String) -> Unit = { _, _ -> },
    val onRenameListClick: (Long) -> Unit = {},
    val onRenameListNameChange: (String) -> Unit = {},
    val onRenameListConfirm: () -> Unit = {},
    val onRenameListDismiss: () -> Unit = {},
)
